--Activity3
SELECT SALESMAN_ID, SALESMAN_CITY FROM SALESMAN;

SELECT * FROM SALESMAN
WHERE SALESMAN_CITY = 'Paris';

SELECT SALESMAN_ID, SALESMAN_COMMISSION FROM SALESMAN
WHERE SALESMAN_NAME = 'Paul Adam';