--Activity 8

SELECT * FROM ORDERS
ORDER BY CUSTOMER_ID;

SELECT CUSTOMER_ID, MAX(PURCHASE_AMOUNT)
FROM ORDERS
GROUP BY CUSTOMER_ID
ORDER BY CUSTOMER_ID;

SELECT SALESMAN_ID, MAX(PURCHASE_AMOUNT)
FROM ORDERS
WHERE ORDER_DATE = '17-AUG-12'
GROUP BY SALESMAN_ID
ORDER BY SALESMAN_ID;

SELECT CUSTOMER_ID, ORDER_DATE, MAX(PURCHASE_AMOUNT)
FROM ORDERS
GROUP BY CUSTOMER_ID, ORDER_DATE
HAVING MAX(PURCHASE_AMOUNT) IN (2030, 3450, 5760, 6000)
ORDER BY CUSTOMER_ID;